# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0ade960523482698c70fa4bb939c5b54"
name = "fruit-shop"
handle = "fruit-shop-1"
application_url = "https://bestsellers-entertaining-auction-excited.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://bestsellers-entertaining-auction-excited.trycloudflare.com/auth/callback",
  "https://bestsellers-entertaining-auction-excited.trycloudflare.com/auth/shopify/callback",
  "https://bestsellers-entertaining-auction-excited.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
